// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwalyfmpmbzxltlnpbma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3YWx5Zm1wbWJ6eGx0bG5wYm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzY2MzAsImV4cCI6MjA3MzcxMjYzMH0.lj4cVsOT0bWBN30vNbieo2qIRh4QRv0Ozq3DD4NvYdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});